#!/bin/sh
set -eu
clang-format *.c *.h -i
clang -nostdinc -I. -I./lua-5.4.6/src -I"$HOME/chibicc" -P -E main.c -o tmp.c
chibicc -O1 tmp.c > tmp.tal
echo '@end' >>tmp.tal
rm tmp.c
uxnasm tmp.tal main.rom
rm tmp.tal
